server:
  port: 6666


spring:
  datasource:
          name: tea
          url: jdbc:mysql://localhost:3306/tea
          username: root
          password: root
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20
#  cache:
#      ehcache:
#        config: classpath:learn/ehcache.xml

  #redis
  redis:
      database: 0
      host: 140.143.242.80
      port: 6379
      password: joejoejoe
      timeout: 0
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0






