spring:
  profiles:
    active: dev

security:
  basic:
    enabled: false

mybatis:
  mapper-locations: classpath:/*/*.xml
  type-aliases-package: com.joe.api.*.po
#  开启mybatis日志打印
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


qiNiu:
  accessKey: qFK5rkWh6ua5Z2WwXItC-bj1MAxklN284aZzGlpc
  secretKey: IQSsg6tKgT4-3IV2U7G_FKFMtVXOA14M7tm2prMJ
  bucketName: mywebt
  macName: HmacSHA1
  encoding: UTF-8
  effective: 3
