
server:
  port: 8888
  ssl:
    key-store: classpath:2525450_www.qiaoyuntea.xyz.pfx
    key-store-password: 9a4kWndC

spring:
    datasource:
        name: tea
        url: jdbc:mysql://39.105.2.84:3306/tea
        username: root
        password: Admin@1234
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      database: 0
      host: localhost
      port: 6379
    freemarker:
      cache: true
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      suffix: .ftl
      template-loader-path: /ftl


qiNiu:
    accessKey: qFK5rkWh6ua5Z2WwXItC-bj1MAxklN284aZzGlpc
    secretKey: IQSsg6tKgT4-3IV2U7G_FKFMtVXOA14M7tm2prMJ
    bucketName: mywebt
    macName: HmacSHA1
    encoding: UTF-8
    effective: 3



