
#默认打包环境
spring:
    profiles:
      active: dev
server:
  context-path: /
#mybatis配置
mybatis:
  mapper-locations: classpath:/*/*.xml
  type-aliases-package: com.joe.api.*.po
#  开启mybatis日志打印
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#七牛配置
qiNiu:
    accessKey: qFK5rkWh6ua5Z2WwXItC-bj1MAxklN284aZzGlpc
    secretKey: IQSsg6tKgT4-3IV2U7G_FKFMtVXOA14M7tm2prMJ
    bucketName: mywebt
    macName: HmacSHA1
    encoding: UTF-8
    effective: 3



wx:
    appId: WX_APP_ID
    secretKey: WX_SECRET_KEY
    grantType: WX_GRANT_TYPE
    charSet: WX_CHAR_SET
    grantUrl: WX_GRANT_URL
    unifiedOrderUrl: WX_UNIFIED_ORDER_API
    reFundUrl: WX_REFUND_URL
    mchId: WEPAY_BUSINESS_CODE
    unifiedKey: WEPAY_UNIFIED_KEY
    notifyUrl: WX_NOTIFY_URL

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/

weChat:
  mpAppId: wx7787aa5b85cd4a58
  secretKey: b0dab0e3e2833d3e8bb20ebd059ca558

