server:
  port: 8080
  ssl:
    key-store: classpath:server.jks
    key-store-password: yvrvl08smap


spring:
    datasource:
        name: tea
        url: jdbc:mysql://140.143.242.80:3306/tea
        username: joe
        password: joejoejoe
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
   #  freemarker 参数
    freemarker:
      cache: true
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      suffix: .ftl
      template-loader-path: /ftl

#    多环境配置
    profiles:
      active: dev


mybatis:
  mapper-locations: classpath:/*/*.xml
  type-aliases-package: com.joe.api.*.po

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#七牛上传文件参数
qiNiu:
    accessKey: qFK5rkWh6ua5Z2WwXItC-bj1MAxklN284aZzGlpc
    secretKey: IQSsg6tKgT4-3IV2U7G_FKFMtVXOA14M7tm2prMJ
    bucketName: mywebt
    macName: HmacSHA1
    encoding: UTF-8
    effective: 3



